# Generated by Django 3.2.3 on 2021-08-23 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='google.jpg', upload_to='profile_pictures')),
                ('gender', models.CharField(max_length=6, null=True)),
                ('email', models.EmailField(default='dj@dj.com', max_length=254)),
                ('worked_for', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('water', models.CharField(blank=True, max_length=50, null=True)),
                ('lunch', models.CharField(blank=True, max_length=50, null=True)),
                ('dinner', models.CharField(blank=True, max_length=50, null=True)),
                ('brakefast', models.CharField(blank=True, max_length=50, null=True)),
                ('refreshment', models.CharField(blank=True, max_length=50, null=True)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('dorm', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
