# Generated by Django 3.2.3 on 2021-08-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceitem',
            old_name='item_type',
            new_name='item_description',
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
