# Generated by Django 3.2.3 on 2021-08-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210818_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='quantity',
            field=models.CharField(max_length=20),
        ),
    ]
