# Generated by Django 3.2.3 on 2021-08-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='google.jpg', upload_to='profile_pictures')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
